### PR TITLE
New parameters for Github-Action Cypress

### PR DESCRIPTION
**Pull request by jotadeoliveira**
- change runs-on ubuntu version 20.04 to 22.04 
- change actions/checkout@v2 to actions/checkout@v3
- change uses cypress-io/github-action@v2 to cypress-io/github-action@v5

Reference new https://github.com/cypress-io/github-action#basic

PS: Desculpa o inglês simples...rs

### CODE REVIEW

**Review by wlsf82 — COMMENTED** [review]
Doesn't it work with the existing versions?

**Comment by jotadeoliveira** [comment]
Yes it works. Anyway, in the content of the reference link, it contains these new values to the parameters.

**Comment by wlsf82** [comment]
Since it works, I won't accept the changes.
When I launch the third version of this course, I'll update that.

**Comment by jotadeoliveira** [comment]
OK! Thank you for reply.

**Pull request closed without merging**
